### ISSUE TITLE
NSInMemoryStoreType question

### ISSUE THREAD

**Issue by sjsoad** [radianttap/RTSwiftCoreDataStack#1]
Hi, I have found your solution for CoreData and I see that you work only with SQLite type of storage. Can your solution work with NSInMemoryStoreType?

**Comment by radianttap** [comment]
I have never used it, this can’t say for certain.

**Comment by radianttap** [comment]
@sjsoad I added preliminary support for in-memory type. It should be fine, do let me know if you find issues.
