### ISSUE TITLE
Can we make it work for encrypted Core Data?

### ISSUE THREAD

**Issue by paragdulam** [radianttap/RTSwiftCoreDataStack#2]
Can we integrate encryptedCoreData GitHub library with this?

**Comment by radianttap** [comment]
I have no idea what 'encryptedCoreData' is..?

**Comment by paragdulam** [comment]
So imagine a scenario where an app that needs encryption sqlite file that CoreData has to access, can this library be compatible with it?

**Comment by radianttap** [comment]
I have never worked with encrypted sqlite, thus I can't tell. Do let me know if you try it out.

**Comment by radianttap** [comment]
This library is pretty much the NSPersistentContainer, but with two NSPSCs. As such, if it works with system APIs, it should work with this as well.
