### ISSUE TITLE
Add support for Swift Package Manager

### ISSUE THREAD

**Issue by jasonsilberman** [radianttap/RTSwiftCoreDataStack#4]
Hi,

This library seems great, but I was wondering if you could add support for Swift Package Manager?

I would love to use your library, but I would rather not have to use Carthage or Cocoapods.

Thanks!

**Comment by radianttap** [comment]
I'm open to pull requests :)

At the moment I know next to nothing about SPM.

**Comment by radianttap** [comment]
Should be working, since version 6.4
